### PR TITLE
Hide verses on TV feed.

### LINKED ISSUE #3: Verses are broken in feed
image

### PR DESCRIPTION
**Pull request by KillerX**
We want to intentionally not show verses in the TV feed, but I still wanted to have a way to look at the data if required thus the `Empty` element.

Fixes #3

### CODE REVIEW

File: client/src/components/Feed/Base.vue [hunk 1]
```diff
@@ -1,19 +1,22 @@
 <template>
     <Quote v-if="entry.type == ContributionTypes.QUOTE" :size="size" :quote="entry" />
     <Information class="m-2 mb-8" v-else-if="entry.type == ContributionTypes.INFORMATION" :size="size" :information="entry" />
+	<Empty v-else-if="entry.type == ContributionTypes.BIBLEVERSE" :entry="entry" />
```
Comment (Dr-Wade) [inline client/src/components/Feed/Base.vue:4]: Any special reason why you created an Empty component rather than just not displaying anything?

Comment (KillerX) [reply client/src/components/Feed/Base.vue:4]: Because I wanted to be able to still inspect things if needed.
